# Exported from Render on 2024-11-28T10:49:04Z
databases:
- name: SQLScraper
  databaseName: dblumenads
  user: punitsirse
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: ClaudeDeploy
  runtime: static
  repo: https://github.com/punitsirse123/ClaudeDeploy
  buildCommand: echo "No build needed"
  staticPublishPath: ./
- type: web
  name: backend
  runtime: python
  repo: https://github.com/punitsirse123/backend
  plan: free
  envVars:
  - key: FLASK_ENV
    sync: false
  - key: FLASK_APP
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: SQLScraper
      property: connectionString
  - key: SECRET_KEY
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
version: "1"
